image: maven:3.6-jdk-11

before_script:
  - 'git config --global user.email "aaronmao.hangzhou@gmail.com"'
  - 'git config --global user.name "Barbadosian"'
  - 'git checkout -B "$CI_BUILD_REF_NAME"'

variables:
  LINK_ARTIFACT: "true"

stages:
  - build
  - release
  - notification

build:
  stage: build
  script:
    - 'mvn -Dpackaging=jar -DgeneratePom=false -s ci_settings.xml install'
  artifacts:
    paths:
      - target/TownyMission*.jar
    expire_in: 1 week

release:
  stage: release
  only:
    - master
  script:
    - 'mvn -B -DscmCommentPrefix="[skip ci]" -DignoreSnapshots=true -Dpackaging=jar -DgeneratePom=false -Dusername=$GIT_USERNAME -Dpassword=$GIT_PASSWORD -s ci_settings.xml release:prepare release:perform'
  artifacts:
    paths:
      - target/TownyMission*.jar
    expire_in: 1 week

success_notification:
  stage: notification
  dependencies:
    - build
  script:
    - chmod +x ./send.sh
    - bash send.sh success $WEBHOOK_URL
  when: on_success
  artifacts:
    paths:
      - target/RPG*
    expire_in: 1 week

fail_notification:
  stage: notification
  dependencies:
    - build
  script:
    - chmod +x ./send.sh
    - bash send.sh failure $WEBHOOK_URL
  when: on_failure

pages:
  stage: notification
  dependencies:
    - build
  script:
    - mvn javadoc:javadoc
    - mv target/site/apidocs/ public/
  artifacts:
    paths:
      - public
  when: on_success