image: maven:3.6-jdk-11

before_script:
  - 'git config --global user.email "aaronmao.hangzhou@gmail.com"'
  - 'git config --global user.name "Barbadosian"'
  - 'git checkout -B "$CI_BUILD_REF_NAME"'

variables:
  LINK_ARTIFACT: "true"

default:
  tags:
    - shell

stages:
  - test
  - build
  - deploy
  - release
  - notification

test:
  stage: test
  script:
    - 'mvn -s ci_settings.xml test'
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/**/TEST-*.xml

build:
  stage: build
  dependencies:
    - test
  script:
    - 'mvn -Dpackaging=jar -DgeneratePom=false -s ci_settings.xml clean package'
  artifacts:
    paths:
      - target/TownyMission*.jar
    expire_in: 1 week
  when: on_success

release:
  stage: release
  dependencies:
    - build
  only:
    - master
  script:
    - 'mvn -B -DscmCommentPrefix="[skip ci]" -DignoreSnapshots=true -Dpackaging=jar -DgeneratePom=false -Dusername=$GIT_USERNAME -Dpassword=$GIT_PASSWORD -s ci_settings.xml release:prepare release:perform'
  artifacts:
    paths:
      - target/TownyMission*.jar
    expire_in: 1 week
  when: on_success

success_notification:
  stage: notification
  tags:
    - shell
  dependencies:
    - build
  script:
    - chmod +x ./send.sh
    - bash send.sh success $WEBHOOK_URL
  when: on_success
  artifacts:
    paths:
      - target/TownyMission*
    expire_in: 1 week

fail_notification:
  stage: notification
  tags:
    - shell
  dependencies:
    - build
  script:
    - chmod +x ./send.sh
    - bash send.sh failure $WEBHOOK_URL
  when: on_failure

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - mvn javadoc:javadoc
    - mv target/site/apidocs public
  artifacts:
    paths:
      - public
  when: on_success