# Database settings
database:
  # The address of the database, in IP or domain name
  address:
  # The port of the database, default should be 3306
  port:
  # The name of the database
  name:
  # The username to access the database
  username:
  # The password to access the database
  password:

# Settings for participants in the sprint/season
participants:
  # How many points does each town has to earn regardless to enter the ranking
  sprintRewardBaseline: 2000
  # How many extra points each town must make when they have multiple members
  # Formula for total reward entry bar is: baseline+(n-1)*scale
  sprintRewardMemberScale: 1500
  # Whether there is a max cap that the entry bar can reach
  sprintRewardBaselineCap: 15000
  # How many required naturepoints are added to the base line for each successive sprint
  sprintBaselineIncrement: 1000

# Mission settings
mission:
  # Cooldown between abort/complete and town getting new mission, in minutes
  cooldown: 30
  # How many missions a town can see
  amount: 14

# Sprint settings
sprint:
  # The current sprint, do not touch unless you know what you are doing
  current: 1
  # Duration of the sprint, in days
  duration: 5
  # Interval between two springs, in days
  interval: 2

season:
  # The current season, do not touch unless you know what you are doing
  current: 1
  # Number of sprints that a season will have
  sprintsPerSeason:
  # The started time of this season, do not touch unless you know what you are doing
  # Changing this might corrupt database and interfere with normal sprint/season progression
  # In Java millisecond datetime format
  startedTime:
  # Interval between two season, in days
  interval: 7

# Interval to check whether a town has timeouted on this current mission, in minutes
checkTimeOutInterval: 60