name: TownyMission
author: Barbadosian
main: world.naturecraft.townymission.TownyMissionBukkit
version: ${project.version}
api-version: 1.13

depend:
  - Vault

softdepend:
  - CMI
  - EssentialsX
  - UltimateVotes
  - MMOItems
  - PlaceholderAPI
  - Towny

permissions:
  townymission.player:
    description: Default player commands
    default: true
  townymission.admin:
    description: Default admin commands
    default: op
  townymission.player.claim:
    description: Can use claim
    default: op
  townymission.player.deposit:
    description: Can use deposit
    default: op
  townymission.player.info:
    description: Can use info
    default: op
  townymission.player.list:
    description: Can use list
    default: op
  townymission.player.rank:
    description: Can use rank
    default: op
  townymission.player.reward:
    description: Can use reward
    default: op
  townymission.admin.mission.abort:
    description: Admin can abort
    default: op
  townymission.admin.mission.list:
    description: Admin can list
    default: op
  townymission.admin.season.pause:
    description: Admin can pause season
    default: op
  townymission.admin.season.point:
    description: Admin can manipuate season point
    default: op
  townymission.admin.season.rank:
    description: Admin can check season rank
    default: op
  townymission.admin.season.start:
    description: Admin can start season
    default: op
  townymission.admin.sprint.point:
    description: Admin can manipuate sprint point
    default: op
  townymission.admin.sprint.rank:
    description: Admin can check sprint rank
    default: op
  townymission.admin.info:
    description: Admin can check town info
    default: op
  townymission.admin.reload:
    description: Admin can reload config
    default: op

commands:
  townymission:
    description: Root command
    aliases: tms
  townymissionadmin:
    description: Admin root command
    aliases: tmsa