# Choose mysql and yaml, MySql is recommended for best compatibility
storage: yaml

# Please make sure that this matches EXACTLY with the file name for the language file without the .yml
language: en_US

# **I would sincerely suggest reading the wiki for what this section means**
# Whether your towny server is spanned across multiple servers
bungeecord:
  # Set to true to enable bungeecord support
  # Remember to place the plugin jar in all the servers where you would like to collect statistics
  # Remember to also put this jar in the bungeecord folder!
  enable: true
  # Whether this is the main server, remember to fill both the main-server and serverName
  #   Remember to also fill in the main-server name on Bungee config
  main-server: true
  # You MUST set this config option after build v2.2.1. Otherwise your plugin will not work.
  server-name: lobby
  # If a cached mission entry fail to send, how long should the server wait before trying to resend them?
  #    The unit is in seconds
  resend-interval: 60
  # There are two options: FIXED and INCREMENTAL
  #    FIXED: for every set resend-interval, the cached missions will be sent again
  #    INCREMENTAl: for every resend-interval*failed-count, the cached mission will be sent again
  resend-method: INCREMENTAL
  # The maximum failed counted for a mission before it is discarded
  hard-discard: -1

# Database settings
database:
  # The address of the database, in IP or domain name
  address: my_db
  # The port of the database, default should be 3306
  port: 3336
  # The name of the database
  name: townymission_db
  # The prefix for the database tables, can be used for sharing a single db for different servers
  # Before v2.1.7, the builtin prefix is townymission_, do not change if you are only running spigot mode
  # or do not plan on sharing a single db for different servers
  prefix: "townymission_"
  # The username to access the database
  username: admin
  # The password to access the database
  password: admin
  # Set this to true to cache database in memory, faster operation at the cost of more memory usage
  mem-cache: true

##########################################################
# The following settings should ONLY be set on main server
##########################################################

# Settings for participants in the sprint/season
participants:
  # How many points does each town has to earn regardless to enter the ranking
  sprintRewardBaseline: 2000
  # How many extra points each town must make when they have multiple members
  # Formula for total reward entry bar is: baseline+(n-1)*scale
  sprintRewardMemberScale: 1500
  # Whether there is a max cap that the entry bar can reach
  sprintRewardBaselineCap: 15000
  # How many required naturepoints are added to the base line for each successive sprint
  sprintBaselineIncrement: 1000

# Mission settings
mission:
  # Cooldown between abort/complete and town getting new mission, in minutes
  cooldown: 30
  # How many missions a town can see, DO NOT CONFIGURE THIS AT THE MOMENT
  amount: 14
  # Configure whether the missions are enabled or not
  types:
    # You have to one of the hooks set to true for missions to be enabled
    #  Example: Even if you set enable to true and CMI/EssentialsX to false, money mission would be disabled
    money:
      enable: true
      hooks:
        CMI: true
        EssentialsX: false
    vote:
      enable: true
      hooks:
        NuVotifier: false
        UltimateVotes: true
    mob:
      enable: true
    expansion:
      enable: true
    resource:
      enable: true
      # **Exception! Even if MMOItems is false, you can still enable VANILLA resource mission by setting enable to true
      hooks:
        MMOItems: true

# Sprint settings
sprint:
  # Duration of the sprint, in days
  duration: 5
  # Interval between two springs, in days
  interval: 2
  rewards:
    # EQUAL, CONTRIBUTIONS, INDIVIDUAL
    # EQUALS means that the reward is distributed evenly among all town members,
    #     whether they actually contributed or not
    # CONTRIBUTIONS means that the reward is distributed according to average contribution
    #     (sum of individual contribution)/(number of mission)
    # INDIVIDUAL means that the listed rewards are given to EACH OF of the members
    #     Warning! Watch out your config, EVERYONE will receive EVERYTHING on the list
    # ** points{} reward category is added to the town directly. It is not affected by this setting
    method: contributions
    # There are only four types, RESOURCE, MONEY, COMMAND, and POINTS
    # Points are the season points used to calculate season rewards below
    # ***---> The numbering for the list means RANK, so the highest ranking town would receive rewards under 1:
    # ***---> If no other: exists, non-rank-specified town would receive nothing fdsd
    # Please use the exact format as the shown in the following default config
    # Placeholders
    #   - %player%: the name of the player, only works in COMMAND type
    rewards:
      # Its a little bit lengthy to put the reward json explanation here.
      # For the details, please visit wiki here https://git.naturecraft.world/naturecraft-dev/townymission/-/wikis/home
      1:
        - 'resource{"type": "DIAMOND", "amount": 100}'
        - 'money{"amount": 50000}'
        - 'command{"command": "cmi msg %player% wow you are amazing"}'
        - 'points{"amount":5}'
      2:
        - 'resource{"type": "DIAMOND", "amount": 100}'
        - 'money{"amount": 50000}'
        - 'command{"command": "cmi msg %player% wow you are amazing"}'
        - 'points{"amount":5}'
      others:
        - 'points{"amount": 1}'


season:
  # Number of sprints that a season will have
  sprintsPerSeason: 4
  # Interval between two season, in days
  interval: 7
  rewards:
    # EQUAL, CONTRIBUTIONS, INDIVIDUAL
    # EQUALS means that the reward is distributed evenly among all town members,
    #     whether they actually contributed or not
    # CONTRIBUTIONS means that the reward is distributed according to average contribution
    #     (sum of individual contribution)/(number of mission)
    # INDIVIDUAL means that the listed rewards are given to EACH OF of the members, whether they actually contributed or not
    #     Warning! Watch out your config, EVERYONE will receive EVERYTHING on the list
    # Command reward type will be given to everyone in EQUAL, and once for people who contributed in CONTRIBUTIONS or INDIVIDUAL
    method: contributions
    # There are only three types, RESOURCE, MONEY, and COMMAND
    # Please use the exact format as the shown in the following default config
    # Placeholders
    #   - %player%: the name of the player, only works in COMMAND type
    rewards:
      # Its a little bit lengthy to put the reward json explanation here.
      # For the details, please visit wiki here https://git.naturecraft.world/naturecraft-dev/townymission/-/wikis/home
      1:
        - 'resource{"type": "DIAMOND", "amount": 100}'
        - 'money{"amount": 50000}'
        - 'command{"command": "cmi msg %player% wow you are amazing", "runDirect": "true", "displayName": "You are Amazing"}'
      others:
        - 'resource{"type": "DIAMOND", "amount": 100}'
        - 'money{"amount": 50000}'
        - 'command{"command": "cmi msg %player% wow you are amazing"}'