name: TownyMission
author: Barbadosian
main: world.naturecraft.townymission.TownyMissionBukkit
version: ${project.version}
api-version: 1.13

depend:
  - Vault

softdepend:
  - CMI
  - EssentialsX
  - UltimateVotes
  - MMOItems
  - PlaceholderAPI
  - Towny

permissions:
  townymission.player:
    description: Default player commands
    default: true
  townymission.admin:
    description: Default admin commands
    default: op
  townymission.premium:
    description: premium reward track
    default: op
  townymission.boost.:
    description: boost permission
  townymission.commands.addpoint:
    description: Add point
    default: op
  townymission.commands.rmpoint:
    description: Remove point
    default: op
  townymission.commands.setpoint:
    description: Set point
    default: op
  townymission.commands.checkpoint:
    description: Check the point
    default: op
  townymission.commands.listall:
    description: Check the point
    default: op

commands:
  townymission:
    description: Root command
    aliases: tms
  townymissionadmin:
    description: Admin root command
    aliases: tmsa